name: Daily Config Update

on:
  schedule:
    # 每天 UTC 时间 12 点运行
    - cron: '0 12 * * *'
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-and-encode:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 代码仓库
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 获取完整历史记录

      - name: 配置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # 使用 Node.js 18.x 版本
          # 移除 npm 缓存配置，避免查找锁文件
          
      - name: 安装 Base58 编码依赖
        run: npm install base58

      - name: 下载并编码配置文件
        run: |
          # 从指定 URL 下载原始配置文件
          curl -s -o configplus_isadult.json "https://download2276.mediafire.com/znbvk8455mxgeu15EJep_sI8XFojGOALt66KPvRyJu_zEFCX_AdkhdO2np9BvLV8FitciNosY26d93Dnp0pA5aWK5SO0VUk6Y6MWucy4xouReq-trK7AbKXjwBYp5-xeterM-ZLHI50gPtgw-3KEjlqi8ROSqJfE9EDRShIlBfcoqaI/ff60ynj6z21iqfb/configplus_isadult.json"
          
          # 使用 Node.js 脚本进行 Base58 编码
          node -e "
            const fs = require('fs');
            const base58 = require('base58');
            // 读取下载的文件内容
            const fileContent = fs.readFileSync('configplus_isadult.json');
            // 进行 Base58 编码
            const encodedContent = base58.encode(fileContent);
            // 将编码结果写入新文件
            fs.writeFileSync('configplus_isadult_base58.json', encodedContent);
            console.log('配置文件已成功编码为 Base58 格式');
          "

      - name: 检查是否有文件变更
        id: check_changes
        run: |
          # 检查编码后的文件是否有修改
          if git diff --quiet HEAD -- configplus_isadult_base58.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 提交并推送变更（如有修改）
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          # 配置 Git 提交信息
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # 添加变更文件
          git add configplus_isadult_base58.json
          # 提交变更，包含时间戳
          git commit -m "Auto-update: configplus_isadult_base58.json $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          # 推送到 main 分支
          git push origin main

      - name: 清理临时文件
        run: |
          # 删除原始下载文件，只保留编码后的文件在仓库中
          rm -f configplus_isadult.json
    
