name: Update Config File

on:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC时间3点运行（注意：UTC时间与您本地时间可能有时差）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Download config file
      run: |
        # 下载文件到临时位置
        curl -s -o /tmp/config_orig.json "https://download2276.mediafire.com/yd29kplgvsugWHwYIbhx5yiHIqoqYtVEuZ2yBLJiXcdVnxh6Gw97v7_uxeo2XVQdLvoxPfrVOGh0P3AofnH7p68-MTzVMog_3n37RB-5qHx-xhcIFOxnNrIAhqPo8W3Q4Xqn-kf8Vum532Ur2_5lQBO7OZnTY_rr-H66Dx29ZiOuZlo/ff60ynj6z21iqfb/configplus_isadult.json"
        
        # 检查文件是否下载成功
        if [ ! -s /tmp/config_orig.json ]; then
          echo "Error: Downloaded file is empty or failed"
          exit 1
        fi

        # 使用Node.js进行Base58编码
        npm install base58
        node -e "
        const fs = require('fs');
        const base58 = require('base58');
        const data = fs.readFileSync('/tmp/config_orig.json');
        const encoded = base58.encode(data);
        fs.writeFileSync('/tmp/config.json', encoded);
        console.log('File encoded successfully');
        "
      
        
    - name: Check if file has changed
      id: file_check
      run: |
        # 检查文件是否存在且内容是否相同
        if [ -f "config.json" ] && cmp -s "/tmp/config.json" "config.json"; then
          echo "文件无变化，无需提交"
          echo "has_changed=false" >> $GITHUB_OUTPUT
        else
          echo "文件有变化，需要提交"
          echo "has_changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Update config file
      if: steps.file_check.outputs.has_changed == 'true'
      run: |
        # 移动文件到仓库根目录
        mv /tmp/config.json config.json
        
    - name: Commit and push changes
      if: steps.file_check.outputs.has_changed == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add config.json
        git commit -m "chore: 自动更新config.json配置文件 [$(date +'%Y-%m-%d %H:%M')]"
        git push origin main
