name: Daily Config Update

on:
  schedule:
    # 每天12点运行 (UTC时间)
    - cron: '0 12 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install base58

    - name: Download and encode config file
      run: |
        # 下载原始文件
        curl -s -o configplus_isadult.json "https://download2276.mediafire.com/znbvk8455mxgeu15EJep_sI8XFojGOALt66KPvRyJu_zEFCX_AdkhdO2np9BvLV8FitciNosY26d93Dnp0pA5aWK5SO0VUk6Y6MWucy4xouReq-trK7AbKXjwBYp5-xeterM-ZLHI50gPtgw-3KEjlqi8ROSqJfE9EDRShIlBfcoqaI/ff60ynj6z21iqfb/configplus_isadult.json"
        
        # 使用Node.js进行Base58编码
        node -e "
        const fs = require('fs');
        const base58 = require('base58');
        const data = fs.readFileSync('configplus_isadult.json');
        const encoded = base58.encode(data);
        fs.writeFileSync('configplus_isadult_base58.json', encoded);
        console.log('File encoded successfully');
        "

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet HEAD -- configplus_isadult_base58.json; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push if changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add configplus_isadult_base58.json
        git commit -m "Auto-update: configplus_isadult_base58.json $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        git push origin main

    - name: Clean up
      run: |
        rm -f configplus_isadult.json
